raise error for nan hidden states (#615)
<!-- markdownlint-disable -->

<!-- PLEASE FILL IN THE PR DESCRIPTION HERE ENSURING ALL CHECKLIST ITEMS
(AT THE BOTTOM) HAVE BEEN CONSIDERED. -->

## Purpose
We had a failure early this week due to hiddenstatesconnector sending
nan hidden states. However, our training kept going. We should
explicitly fair when getting garbage hidden states

## Tests
Tested locally and ran the e2e smoke tests.

Now failes directly:
``` bash
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shanjiaz/speculators/src/speculators/train/data.py", line 327, in _maybe_generate_hs
    check_hidden_states(loaded_hs, dataset_item["input_ids"].tolist())
  File "/home/shanjiaz/speculators/src/speculators/data_generation/offline.py", line 17, in check_hidden_states
    raise ValueError("Hidden states contain NaN values")
ValueError: Hidden states contain NaN values
================================================== 1 failed, 16 warnings in 180.86s (0:03:00) ==================================================
```

## Checklist

I have filled in:

- [x] The purpose of the PR, such as "Fix some issue (link existing
issues this PR will resolve)".
- [x] The test plan/results, such as providing test command and pasting
the results.
- [ ] (Optional) The necessary documentation update.
- [x] I (a human) have written or reviewed the code in this pr to the
best of my ability.

---------

Signed-off-by: shanjiaz <hezhao@redhat.com>
Co-authored-by: shanjiaz <hezhao@redhat.com>