remove forcing --enable-chunked-prefill to false (#1205)
<!-- markdownlint-disable -->

<!-- PLEASE FILL IN THE PR DESCRIPTION HERE ENSURING ALL CHECKLIST ITEMS
(AT THE BOTTOM) HAVE BEEN CONSIDERED. -->

## Purpose
Remove forcing --enable-chunked-prefill to false due to vllm
https://github.com/vllm-project/vllm/pull/50991 to fix e2e test failure:

```
(APIServer pid=19327) pydantic_core._pydantic_core.ValidationError: 1 validation error for VllmConfig
(APIServer pid=19327)   Assertion failed, Chunked prefill is required for mamba cache mode 'align'. [type=assertion_error, input_value=ArgsKwargs((), {'model_co... 'shutdown_timeout': 0}), input_type=ArgsKwargs]

FAILED tests/e2e/smoke/test_mtp_finetuning.py::test_mtp_finetuning_smoke - RuntimeError: vLLM server process exited with code 1 before becoming ready
```

## Tests
Kicked off a run from the PR:
https://github.com/neuralmagic/llm-compressor-testing/actions/runs/37663275323

## Checklist

I have filled in:

- [ ] The purpose of the PR, such as "Fix some issue (link existing
issues this PR will resolve)".
- [ ] The test plan/results, such as providing test command and pasting
the results.
- [ ] (Optional) The necessary documentation update.
- [ ] I (a human) have written or reviewed the code in this pr to the
best of my ability.

Signed-off-by: Dan Huang <dahuang@redhat.com>